# Generated by Django 5.1.3 on 2025-02-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sudoku', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='score',
            new_name='current_score',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='time',
            new_name='current_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='game_state',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='current_game_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='current_solution',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='difficulty_level',
            field=models.CharField(default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_game_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
